name: kiss-lint

on: [push, pull_request]

jobs:
  shellcheck:
    name: kiss-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run kiss-lint.
        run: |
          ./lint
